name: The Social Field Guide
favicon: null
layout_spectrum: 0.3453955452423543
typography_spectrum: 0.21301504620350897
title: The Social Field Guide
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#206a49'
    - '#fcfef1'
    - '#a7aab1'
    - '#d10121'
  brandStrength: 0.47728294180706143
  lightness: 0.3906825822778046
  saturation: 0.8601758724544197
  rhythmicContrast: 0.9671406028792262
purpose: []
